<?php
/**
 * Light TMS - Diccionario de datos del RNDC (variables oficiales).
 * GENERADO desde 'Maestro_Diccionario de Datos_RNDC.csv'. No editar a mano.
 *
 * [procesoid => ['nombre'=>..., 'campos'=>[ [variable, requerido, tipo, tamano, etiqueta, orden], ... ]]]
 * requerido: S=obligatorio, N=no, C=condicional.
 */

declare(strict_types=1);

return [
    11 => [
        'nombre' => 'Tercero',
        'campos' => [
            ['NUMNITEMPRESATRANSPORTE', 'S', 'Varchar', '15', 'Nit Empresa', 1],
            ['CODTIPOIDTERCERO', 'S', 'Varchar', '1', 'Tipo Identificación', 10],
            ['TIPOIDTERCERO', 'N', 'Varchar', '80', 'Tipo Identificación', 11],
            ['NUMIDTERCERO', 'S', 'Varchar', '15', 'Número Identificación', 20],
            ['NOMIDTERCERO', 'S', 'Varchar', '100', 'Nombre', 30],
            ['LONGITUD', 'C', 'Numérico', '13', 'Longitud', 40],
            ['LATITUD', 'C', 'Numérico', '13', 'Latitud', 40],
            ['PRIMERAPELLIDOIDTERCERO', 'C', 'Varchar', '100', 'Primer Apellido', 40],
            ['REGIMENSIMPLE', 'C', 'Varchar', '13', 'Regimen Simple', 41],
            ['SEGUNDOAPELLIDOIDTERCERO', 'N', 'Varchar', '100', 'Segundo Apellido', 50],
            ['CODSEDETERCERO', 'C', 'Varchar', '6', 'Sede', 60],
            ['NOMSEDETERCERO', 'C', 'Varchar', '20', 'Nombre Sede', 70],
            ['NUMTELEFONOCONTACTO', 'C', 'Varchar', '10', 'Teléfono Fijo', 80],
            ['NUMCELULARPERSONA', 'C', 'Varchar', '10', 'Celular', 90],
            ['NOMENCLATURADIRECCION', 'S', 'Varchar', '120', 'Dirrección', 100],
            ['MUNICIPIORNDC', 'S', 'Varchar', '8', 'Municipio', 110],
            ['CODMUNICIPIORNDC', 'S', 'Numérico', '8', 'Código Municipio', 120],
            ['NOMCATEGORIALICENCIACONDUCCION', 'C', 'Varchar', '3', 'Categoría Licencia', 130],
            ['NUMLICENCIACONDUCCION', 'C', 'Varchar', '20', 'Número Licencia', 140],
            ['FECHAVENCIMIENTOLICENCIA', 'S', 'Fecha', '10', 'Fecha Vencimiento', 160],
        ],
    ],
    12 => [
        'nombre' => 'Vehículo',
        'campos' => [
            ['NUMNITEMPRESATRANSPORTE', 'S', 'Varchar', '11', 'Nit Empresa', 1],
            ['NUMPLACA', 'S', 'Varchar', '6', 'Placa', 10],
            ['CODCONFIGURACIONUNIDADCARGA', 'S', 'Numérico', '2', 'Configuración', 20],
            ['CONFIGURACIONUNIDADCARGA', 'C', 'Varchar', '80', 'Configuración Unidad Carga', 21],
            ['MARCAVEHICULOCARGA', 'S', 'Varchar', '30', 'Marca', 30],
            ['CODMARCAVEHICULOCARGA', 'S', 'Numérico', '10', 'Marca', 30],
            ['LINEAVEHICULOCARGA', 'C', 'Varchar', '30', 'Línea', 40],
            ['CODLINEAVEHICULOCARGA', 'C', 'Numérico', '10', 'Línea', 40],
            ['NUMEJES', 'C', 'Numérico', '2', 'Número Ejes', 50],
            ['ANOFABRICACIONVEHICULOCARGA', 'S', 'Numérico', '4', 'Modelo', 60],
            ['ANOREPOTENCIACION', 'C', 'Numérico', '4', 'Repotenciado a', 70],
            ['CODCOLORVEHICULOCARGA', 'C', 'Numérico', '5', 'Color', 80],
            ['ASEGURADORASOAT', 'C', 'Varchar', '80', 'ASEGURADORASOAT', 82],
            ['COLORVEHICULOCARGA', 'C', 'Varchar', '80', 'COLOR', 82],
            ['PESOVEHICULOVACIO', 'S', 'Numérico', '5', 'Peso Vacío', 90],
            ['CAPACIDADUNIDADCARGA', 'C', 'Numérico', '5', 'Capacidad', 100],
            ['CODTIPOCARROCERIA', 'C', 'Numérico', '3', 'Carrocería', 110],
            ['NUMCHASIS', 'C', 'Varchar', '50', 'Serie', 120],
            ['TIPOCARROCERIA', 'C', 'Varchar', '80', 'TipoCarroceria', 120],
            ['CODTIPOCOMBUSTIBLE', 'C', 'Varchar', '2', 'Tipo Combustible', 130],
            ['TIPOCOMBUSTIBLE', 'C', 'Varchar', '80', 'TIPO COMBUSTIBLE', 134],
            ['NUMSEGUROSOAT', 'C', 'Varchar', '15', 'Número Póliza', 140],
            ['FECHAVENCIMIENTOSOAT', 'C', 'Varchar', '10', 'Fecha de Vencimiento', 150],
            ['NUMNITASEGURADORASOAT', 'C', 'Numérico', '11', 'Aseguradora', 160],
            ['CODTIPOIDPROPIETARIO', 'S', 'Varchar', '1', 'Tipo Identificación', 170],
            ['TIPOIDPROPIETARIO', 'C', 'Varchar', '80', 'TipoIdPropietario', 175],
            ['TIPOIDTENEDOR', 'C', 'Varchar', '80', 'TipoIdTenedor', 175],
            ['NUMIDPROPIETARIO', 'S', 'Varchar', '15', 'Número Identificación', 180],
            ['CODTIPOIDTENEDOR', 'S', 'Varchar', '1', 'Tipo Identificación', 190],
            ['NUMIDTENEDOR', 'S', 'Varchar', '15', 'Número Identificación', 200],
        ],
    ],
    3 => [
        'nombre' => 'Remesa Terrestre de Carga',
        'campos' => [
            ['DESCRIPCIONDETALLADARESIDUO', 'N', 'Varchar', '100', 'Nombre Residuo Pelig.', 1],
            ['NOMBRENEP', 'N', 'Varchar', '100', 'Nombre NEP', 1],
            ['PELIGROSIDAD', 'N', 'Varchar', '3', 'Peligrosidad', 2],
            ['RESIDUODESAGREGACION', 'N', 'Varchar', '10', 'Desagreg. Corriente Res. Pel.', 4],
            ['RESIDUO', 'N', 'Varchar', '6', 'Codigo Residuo', 4],
            ['CANTIDADPRODUCTO', 'N', 'Numérico', '6', 'Cantidad Producto', 5],
            ['UNIDADMEDIDAPRODUCTO', 'N', 'Varchar', '6', 'U/M Producto', 6],
            ['GRUPOEMBALAJEENVASE', 'N', 'Varchar', '3', 'Grupo Embalaje/Envase', 7],
            ['ESTADOMERCANCIA', 'N', 'Varchar', '1', 'Estado Mercancia', 8],
            ['CODIGOUN', 'N', 'Varchar', '5', 'Codigo UN', 9],
            ['TIPOCONSOLIDADA', 'N', 'Varchar', '1', 'Tipo Consolidada', 10],
            ['NUMNITEMPRESATRANSPORTE', 'N', 'Numérico', '11', 'NIT', 10],
            ['CONTENEDORSERIAL', 'N', 'Varchar', '11', 'Numero Serial Contenedor', 20],
            ['CONSECUTIVOREMESA', 'S', 'Varchar', '15', 'Consecutivo', 20],
            ['REMORDENCARGALISTA', 'N', 'Varchar', '80', 'Información del Viaje', 30],
            ['REMNROPREREMESALISTA', 'N', 'Varchar', '80', 'Información de Carga', 40],
            ['REMNROPREREMESA', 'N', 'Varchar', '15', 'Consecutivo Información de Carga', 50],
            ['MANNOMBREMARCA', 'N', 'Varchar', '15', 'Información de Carga a Dividir', 55],
            ['REMPREREMESADIVIDIDA', 'N', 'Varchar', '15', 'Información de Carga a Dividir', 55],
            ['CODOPERACIONTRANSPORTE', 'S', 'Varchar', '1', 'Tipo Operación', 60],
            ['TIPOEMPAQUE', 'S', 'Varchar', '2', 'Tipo Empaque', 70],
            ['CODNATURALEZACARGA', 'S', 'Numérico', '1', 'Naturaleza Carga', 80],
            ['DESCRIPCIONCORTAPRODUCTO', 'S', 'Varchar', '60', 'Descripción Corta Producto', 90],
            ['CAPITULO', 'N', 'Varchar', '120', 'Clasificación', 100],
            ['PARTIDA', 'N', 'Varchar', '120', 'Nombre', 110],
            ['MERCANCIAREMESA', 'S', 'Varchar', '6', 'Código Producto', 120],
            ['REMCANTIDAD', 'C', 'Numérico', '6', 'Cantidad Estimada', 130],
            ['CANTIDADCARGADA', 'N', 'Numérico', '6', 'Cantidad Cargada', 135],
            ['UNIDADMEDIDACAPACIDAD', 'C', 'Numérico', '1', 'Unidad de Medida', 140],
            ['PESOCONTENEDORVACIO', 'C', 'Numérico', '5', 'Peso Contenedor Vacío', 150],
            ['TIPOIDPROPIETARIO', 'S', 'Varchar', '1', 'Tipo Identificación', 152],
            ['NUMIDPROPIETARIO', 'S', 'Varchar', '15', 'Número Identificación', 154],
            ['CODSEDEPROPIETARIO', 'C', 'Varchar', '4', 'Sede', 156],
            ['REMSEDEPROPIETARIOLISTA', 'C', 'Varchar', '80', 'Sede', 158],
            ['CODTIPOIDREMITENTE', 'S', 'Varchar', '1', 'Tipo Identificación', 160],
            ['REMIDENREMITENTE', 'S', 'Varchar', '15', 'Número Identificación', 170],
            ['REMSEDEREMITENTE', 'C', 'Varchar', '4', 'Sede', 180],
            ['REMSEDEREMITENTELISTA', 'C', 'Varchar', '80', 'Sede', 183],
            ['CODTIPOIDDESTINATARIO', 'S', 'Varchar', '1', 'Tipo Identificación', 190],
            ['NUMIDDESTINATARIO', 'S', 'Varchar', '15', 'Número Identificación', 200],
            ['CODSEDEDESTINATARIO', 'C', 'Numérico', '4', 'Sede', 210],
            ['REMSEDEDESTINATARIOLISTA', 'C', 'Varchar', '80', 'Sede', 213],
            ['REMDUENOPOLIZA', 'S', 'Varchar', '1', 'Tomador de la Póliza', 220],
            ['REMPOLIZA', 'C', 'Varchar', '20', 'Póliza Número', 240],
            ['REMVENCIMIENTO', 'C', 'Fecha', '10', 'Fecha Vencimiento', 250],
            ['REMASEGURADORA', 'C', 'Numérico', '11', 'Aseguradora', 260],
            ['REMHORASPACTOCARGA', 'N', 'Numérico', '3', 'Horas Totales Cargue Pactadas', 330],
            ['REMMINUTOSPACTOCARGA', 'N', 'Numérico', '2', 'Minutos Totales Cargue Pactados', 340],
            ['REMHORASPACTODESCARGA', 'S', 'Numérico', '3', 'Horas Totales Descargue Pactadas', 350],
            ['REMMINUTOSPACTODESCARGA', 'S', 'Numérico', '2', 'Minutos Totales Descargue Pactados', 360],
            ['REMHORASREALCARGA', 'N', 'Numérico', '2', 'Horas Totales Cargue Ejecutadas', 370],
            ['REMMINUTOSREALCARGA', 'N', 'Numérico', '2', 'Minutos Totales Cargue Ejecutados', 380],
            ['OBSERVACIONES', 'N', 'Varchar', '200', 'Recomendaciones', 390],
            ['FECHACITACARGUE', 'S', 'Fecha', '10', 'Fecha Cita Cargue', 500],
            ['FECHACITADESCARGUE', 'S', 'Fecha', '10', 'Fecha Cita Descargue', 501],
            ['HORACITACARGUE', 'S', 'Varchar', '5', 'Hora Cita Cargue', 502],
            ['HORACITADESCARGUE', 'S', 'Varchar', '5', 'Hora Cita Descargue', 503],
            ['PERMISOCARGAEXTRA', 'N', 'Varchar', '15', 'Permiso Carga Extra', 600],
            ['SUBPARTIDA_CODE', 'N', 'Varchar', '2', 'Subpartida', 650],
            ['CODIGOARANCEL_CODE', 'N', 'Varchar', '2', 'Codigo Arancel', 660],
        ],
    ],
    4 => [
        'nombre' => 'Manifiesto de Carga',
        'campos' => [
            ['ACEPTACIONELECTRONICA', 'N', 'Varchar', '2', 'Aceptación Electrónica', 0],
            ['MANNROPOLIZA', 'S', 'Varchar', '20', 'Nro Póliza', 0],
            ['MANCAPACIDAD', 'N', 'Numérico', '5', 'Capacidad', 0],
            ['MANMODELO', 'N', 'Numérico', '4', 'Modelo', 0],
            ['MANCONFIGURACION', 'N', 'Numérico', '2', 'Configuración', 0],
            ['MANMARCA', 'N', 'Numérico', '5', 'Marca', 0],
            ['MANCANTIDADREMESAS', 'N', 'Numérico', '3', 'Cantidad de Remesas', 0],
            ['MANHORASPACTODESCARGA', 'N', 'Numérico', '2', 'Horas Totales Descargue (incluye Espera + Descargue)', 0],
            ['MANHORASPACTOCARGA', 'N', 'Numérico', '2', 'Horas Totales Cargue (incluye Espera + Cargue)', 0],
            ['MANPESO', 'N', 'Numérico', '5', 'Peso Vacío', 0],
            ['NITMONITOREOFLOTA', 'N', 'Varchar', '15', 'Nit Monitoreo Flota', 1],
            ['CODVIA', 'S', 'Numérico', '6', 'Codigo VIA', 5],
            ['NUMNITEMPRESATRANSPORTE', 'S', 'Numérico', '11', 'NIT', 10],
            ['NUMMANIFIESTOCARGA', 'S', 'Varchar', '15', 'Consecutivo', 20],
            ['CONSECUTIVOINFORMACIONVIAJE', 'N', 'Varchar', '15', 'Información de Viaje', 30],
            ['MANNROMANIFIESTOTRANSBORDO', 'N', 'Varchar', '15', 'Manifiesto de Carga del Transbordo', 35],
            ['CODOPERACIONTRANSPORTE', 'S', 'Varchar', '1', 'Tipo Manifiesto', 40],
            ['FECHAEXPEDICIONMANIFIESTO', 'S', 'Fecha', '10', 'Fecha Expedición', 50],
            ['MANORIGEN', 'S', 'Varchar', '60', 'Origen', 70],
            ['CODMUNICIPIOORIGENMANIFIESTO', 'S', 'Numérico', '8', 'Origen', 80],
            ['TIPOVALORPACTADO', 'N', 'Varchar', '1', 'Tipo ValorPactado', 81],
            ['VIAJESDIA', 'N', 'Numérico', '8', 'Viajes Dia', 81],
            ['CODMUNICIPIOINTERMEDIO', 'N', 'Numérico', '8', 'Municipio Intermedio', 81],
            ['MANDESTINO', 'S', 'Varchar', '60', 'Destino', 90],
            ['CODMUNICIPIODESTINOMANIFIESTO', 'S', 'Numérico', '8', 'Destino', 100],
            ['CODIDTITULARMANIFIESTO', 'S', 'Varchar', '1', 'Tipo Identificación', 110],
            ['NUMIDTITULARMANIFIESTO', 'S', 'Varchar', '15', 'Número Identificación', 120],
            ['NUMPLACA', 'S', 'Varchar', '6', 'Placa Vehículo', 130],
            ['NUMPLACAREMOLQUE', 'C', 'Varchar', '6', 'Placa Remolque/Semiremolque', 140],
            ['TIPOIDCONDUCTOR', 'S', 'Varchar', '1', 'Tipo Identificación', 150],
            ['NUMIDCONDUCTOR', 'S', 'Varchar', '15', 'Número Identificación', 160],
            ['VALORFLETEPACTADOVIAJE', 'S', 'Numérico', '11', 'Valor a pagar por el Viaje', 170],
            ['RETENCIONFUENTEMANIFIESTO', 'S', 'Numérico', '11', 'Retención en la Fuente', 180],
            ['RETENCIONICAMANIFIESTOCARGA', 'S', 'Numérico', '4.2', 'Retención ICA ($/mil)', 190],
            ['MANDESCU_LEY', 'N', 'Numérico', '11', 'Retención ICA', 200],
            ['MANVLRTOTFLETE', 'N', 'Numérico', '11', 'Neto a Pagar', 210],
            ['VALORANTICIPOMANIFIESTO', 'N', 'Numérico', '11', 'Valor Anticipo', 220],
            ['MANSALDO', 'N', 'Numérico', '11', 'Saldo x Pagar', 230],
            ['MUNICIPIOPAGOSALDO', 'S', 'Varchar', '50', 'Lugar Pago del Saldo', 240],
            ['CODMUNICIPIOPAGOSALDO', 'S', 'Numérico', '8', 'Lugar Pago del Saldo', 250],
            ['FECHAPAGOSALDOMANIFIESTO', 'S', 'Fecha', '10', 'Fecha Pago del Saldo', 260],
            ['RESPONSABLEPAGOCARGUE', 'S', 'Varchar', '1', 'Responsable pago Cargue', 270],
            ['RESPONSABLEPAGODESCARGUE', 'S', 'Varchar', '1', 'Responsable pago Descargue', 280],
            ['OBSERVACIONES', 'N', 'Varchar', '200', 'Recomendaciones', 290],
            ['REMESASMAN', 'S', ' ', '0', 'Asociar Remesas', 300],
            ['MANLISTAREMESAS', 'S', 'Varchar', '120', 'Remesas', 310],
        ],
    ],
];
