-- Light TMS - Catálogo de configuración de unidad de carga (vehículo).
SET NAMES utf8mb4;
DROP TABLE IF EXISTS configuracion_vehiculo;
CREATE TABLE configuracion_vehiculo (id INT AUTO_INCREMENT PRIMARY KEY, codigo VARCHAR(3) NOT NULL, nombre VARCHAR(10) NULL, descripcion VARCHAR(120) NULL, tipo VARCHAR(40) NULL, KEY idx_cfg_cod (codigo)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO configuracion_vehiculo (codigo, nombre, descripcion, tipo) VALUES
('28','SM9','SemiRemolque Modular de 9 ejes','SemiRemolque Modular'),
('27','SM8','SemiRemolque Modular de 8 ejes','SemiRemolque Modular'),
('26','SM7','SemiRemolque Modular de 7 ejes','SemiRemolque Modular'),
('25','SM6','SemiRemolque Modular de 6 ejes','SemiRemolque Modular'),
('24','SM5','SemiRemolque Modular de 5 ejes','SemiRemolque Modular'),
('23','SM4','SemiRemolque Modular de 4 ejes','SemiRemolque Modular'),
('22','SM3','SemiRemolque Modular de 3 ejes','SemiRemolque Modular'),
('21','SM2','SemiRemolque Modular de 2 ejes','SemiRemolque Modular'),
('20','SM1','SemiRemolque Modular de 1 eje','SemiRemolque Modular'),
('10','RM9','Remolque Modular de 9 ejes','Remolque Modular'),
('10','RM8','Remolque Modular de 8 ejes','Remolque Modular'),
('10','RM7','Remolque Modular de 7 ejes','Remolque Modular'),
('10','RM6','Remolque Modular de 6 ejes','Remolque Modular'),
('10','RM5','Remolque Modular de 5 ejes','Remolque Modular'),
('10','RM4','Remolque Modular de 4 ejes','Remolque Modular'),
('10','RM3','Remolque Modular de 3 ejes','Remolque Modular'),
('10','RM2','Remolque Modular de 2 ejes','Remolque Modular'),
('10','RM1','Remolque Modular de 1 eje','Remolque Modular'),
('47','V4','Volqueta de 4 ejes','Rígido'),
('49','V3','Volqueta de 3 ejes','Rígido'),
('48','V2','Volqueta de 2 ejes','Rígido'),
('45','CA','Camioneta de 2 ejes','Rígido'),
('40','M2','Motocarro de 2 ejes','Rígido'),
('85','B5','Remolque Balanceado de más de 4 ejes','Remolque Balanceado'),
('84','B4','Remolque Balanceado de 4 ejes','Remolque Balanceado'),
('74','R5','Remolque de más de 4 ejes','Remolque'),
('54','3S','Tractocamión de 3 ejes','Cabezote'),
('53','2S','Tractocamión de 2 ejes','Cabezote'),
('56','5','Camión Rígido de más de 4 ejes','Rígido'),
('55','4S','Tractocamión de más de 3 ejes','Cabezote'),
('64','S4','Semiremolque de más de 3 ejes','Semiremolque'),
('83','B3','Remolque Balanceado de 3 ejes','Remolque Balanceado'),
('63','S3','Semiremolque de 3 ejes','Semiremolque'),
('52','4','Camión Rígido de 4 ejes','Rígido'),
('73','R4','Remolque de 4 ejes','Remolque'),
('72','R3','Remolque de 3 ejes','Remolque'),
('82','B2','Remolque Balanceado de 2 ejes','Remolque Balanceado'),
('81','B1','Remolque Balanceado de 1 eje','Remolque Balanceado'),
('71','R2','Remolque de 2 ejes','Remolque'),
('62','S2','Semiremolque de 2 ejes','Semiremolque'),
('61','S1','Semiremolque de 1 eje','Semiremolque'),
('51','3','Camión Rígido de 3 ejes','Rígido'),
('50','2','Camión Rígido de 2 ejes','Rígido');
